# Generated by Django 3.2.7 on 2021-09-02 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('instiution', models.CharField(choices=[('CO', 'Company'), ('MB', 'Microfinance Bank'), ('CS', 'Cooperative Societies'), ('FB', 'Financial Banking'), ('IC', 'Insurance Companies')], default='CO', max_length=2)),
                ('list_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('address', models.CharField(max_length=255, null=True)),
                ('start_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('is_saturday_available', models.BooleanField(default=False)),
                ('start_time_sat', models.TimeField()),
                ('close_time_sat', models.TimeField()),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.FloatField()),
                ('freqency_type', models.CharField(max_length=15)),
                ('percentage_return', models.FloatField()),
                ('max_amount', models.FloatField()),
                ('min_amount', models.FloatField()),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='listings.listings')),
            ],
        ),
    ]
