# Generated by Django 3.2.7 on 2021-09-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listings',
            options={'verbose_name_plural': 'Listings'},
        ),
        migrations.AlterModelOptions(
            name='plans',
            options={'verbose_name_plural': 'Plans'},
        ),
        migrations.AlterField(
            model_name='listings',
            name='list_image',
            field=models.ImageField(blank=True, null=True, upload_to='listing'),
        ),
        migrations.AlterField(
            model_name='plans',
            name='plan_image',
            field=models.ImageField(blank=True, null=True, upload_to='plans'),
        ),
    ]
