# Generated by Django 3.2.7 on 2021-09-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20210908_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='instiution',
            field=models.CharField(choices=[('MB', 'Microfinance Bank'), ('CS', 'Cooperative Societies'), ('FB', 'Financial Banking'), ('IC', 'Insurance Companies')], max_length=2),
        ),
    ]
