# Generated by Django 3.2.7 on 2021-09-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listings_instiution'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlansCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Plans Categories',
            },
        ),
        migrations.AlterField(
            model_name='plans',
            name='plan_type',
            field=models.CharField(max_length=266),
        ),
    ]
