# Generated by Django 3.2.7 on 2021-09-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_rename_instiution_listings_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='description',
            field=models.TextField(default='eee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listings',
            name='address',
            field=models.CharField(default='ddddd', max_length=150),
            preserve_default=False,
        ),
    ]
