# Generated by Django 3.2.7 on 2021-09-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20210909_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'InstitutionsType',
            },
        ),
        migrations.RemoveField(
            model_name='listings',
            name='close_time_sat',
        ),
        migrations.RemoveField(
            model_name='listings',
            name='is_saturday_available',
        ),
        migrations.RemoveField(
            model_name='listings',
            name='start_time_sat',
        ),
    ]
