# Generated by Django 3.2.7 on 2021-09-14 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20210914_1034'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlansCategory',
            new_name='PlanCategory',
        ),
    ]
