# Generated by Django 3.2.7 on 2021-09-14 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_rename_planscategory_plancategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstitutionType',
            new_name='InstitutionCategory',
        ),
        migrations.AlterModelOptions(
            name='institutioncategory',
            options={'verbose_name_plural': 'InstitutionsCategories'},
        ),
    ]
