# Generated by Django 3.2.7 on 2021-09-14 12:16

from django.db import migrations, models
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_auto_20210914_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institutioncategory',
            options={'verbose_name_plural': 'Institutions Categories'},
        ),
        migrations.AlterField(
            model_name='listings',
            name='institution',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='listings',
            name='list_image',
            field=models.ImageField(blank=True, null=True, upload_to=listings.models.listing_directory_path),
        ),
    ]
