# Generated by Django 3.2.6 on 2021-09-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('address', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
