# Generated by Django 3.2.6 on 2021-08-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='list_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
