# Generated by Django 3.2.6 on 2021-09-01 17:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.CharField(default=datetime.datetime(2021, 9, 1, 17, 45, 18, 772627, tzinfo=utc), max_length=100),
        ),
    ]
