# Generated by Django 3.2.6 on 2021-08-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=23, max_length=150, verbose_name='username'),
            preserve_default=False,
        ),
    ]
