# Generated by Django 3.2.7 on 2021-09-02 05:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.CharField(default=datetime.datetime(2021, 9, 2, 5, 48, 3, 756503, tzinfo=utc), max_length=100),
        ),
    ]
