# Generated by Django 3.2.6 on 2021-08-17 12:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.CharField(default=datetime.datetime(2021, 8, 17, 12, 56, 10, 79190, tzinfo=utc), max_length=100),
        ),
    ]
