# Generated by Django 3.2.6 on 2021-08-30 09:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.CharField(default=datetime.datetime(2021, 8, 30, 9, 3, 42, 207472, tzinfo=utc), max_length=100),
        ),
    ]
